# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Alchemy-PhotoGallery
version:      0.11
version_from: lib/Alchemy/PhotoGallery.pm
installdirs:  site
requires:
    File::Find::Rule:              0
    Image::ExifTool:               0
    Image::Magick:                 0
    KrKit:                         0
    POSIX:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
